-- Probe Panel V1 initial PostgreSQL schema.
-- All UUID values are generated by the Go applications. No PostgreSQL extension is required.
-- TIMESTAMPTZ stores absolute instants; applications and database sessions must use UTC.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    checksum TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT schema_migrations_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT schema_migrations_checksum_not_blank CHECK (btrim(checksum) <> '')
);

CREATE TABLE users (
    id UUID PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT users_role_valid CHECK (role IN ('viewer', 'admin')),
    CONSTRAINT users_updated_after_created CHECK (updated_at >= created_at)
);

CREATE TABLE nodes (
    id UUID PRIMARY KEY,
    display_name TEXT NOT NULL,
    hostname TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    config_version BIGINT NOT NULL DEFAULT 1,
    agent_version TEXT,
    operating_system TEXT,
    architecture TEXT,
    country_code TEXT,
    region_key TEXT,
    location TEXT,
    enrolled_at TIMESTAMPTZ,
    last_received_at TIMESTAMPTZ,
    last_agent_time TIMESTAMPTZ,
    last_accepted_sequence BIGINT NOT NULL DEFAULT 0,
    last_source_ip INET,
    clock_status TEXT NOT NULL DEFAULT 'unknown',
    clock_skew_seconds BIGINT,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT nodes_display_name_not_blank CHECK (btrim(display_name) <> ''),
    CONSTRAINT nodes_hostname_not_blank CHECK (hostname IS NULL OR btrim(hostname) <> ''),
    CONSTRAINT nodes_country_code_valid CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT nodes_region_key_not_blank CHECK (region_key IS NULL OR btrim(region_key) <> ''),
    CONSTRAINT nodes_location_not_blank CHECK (location IS NULL OR btrim(location) <> ''),
    CONSTRAINT nodes_config_version_positive CHECK (config_version > 0),
    CONSTRAINT nodes_last_sequence_nonnegative CHECK (last_accepted_sequence >= 0),
    CONSTRAINT nodes_clock_status_valid CHECK (clock_status IN ('unknown', 'ok', 'skewed')),
    CONSTRAINT nodes_updated_after_created CHECK (updated_at >= created_at)
);

CREATE FUNCTION valid_agent_mountpoints(mountpoints TEXT[])
RETURNS BOOLEAN
LANGUAGE SQL
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
    SELECT cardinality(mountpoints) BETWEEN 1 AND 32
        AND '/' = ANY(mountpoints)
        AND NOT EXISTS (
            SELECT 1
            FROM unnest(mountpoints) AS value(mountpoint)
            WHERE mountpoint = ''
                OR left(mountpoint, 1) <> '/'
                OR char_length(mountpoint) > 4096
                OR mountpoint ~ E'[\\r\\n]'
        )
        AND cardinality(mountpoints) = (
            SELECT count(DISTINCT mountpoint)
            FROM unnest(mountpoints) AS value(mountpoint)
        );
$$;

CREATE TABLE node_agent_settings (
    node_id UUID PRIMARY KEY REFERENCES nodes(id) ON DELETE CASCADE,
    collect_interval_seconds INTEGER NOT NULL DEFAULT 5,
    report_interval_seconds INTEGER NOT NULL DEFAULT 10,
    mountpoints TEXT[] NOT NULL DEFAULT ARRAY['/']::TEXT[],
    include_virtual_interfaces BOOLEAN NOT NULL DEFAULT FALSE,
    config_refresh_interval_seconds INTEGER NOT NULL DEFAULT 60,
    max_memory_queue_seconds INTEGER NOT NULL DEFAULT 300,
    max_batch_samples INTEGER NOT NULL DEFAULT 120,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT node_agent_settings_intervals_valid CHECK (
        collect_interval_seconds BETWEEN 5 AND 300
        AND report_interval_seconds BETWEEN collect_interval_seconds AND 300
    ),
    CONSTRAINT node_agent_settings_mountpoints_valid CHECK (valid_agent_mountpoints(mountpoints)),
    CONSTRAINT node_agent_settings_refresh_valid CHECK (config_refresh_interval_seconds BETWEEN 10 AND 86400),
    CONSTRAINT node_agent_settings_queue_valid CHECK (max_memory_queue_seconds BETWEEN 1 AND 300),
    CONSTRAINT node_agent_settings_batch_valid CHECK (max_batch_samples BETWEEN 1 AND 120),
    CONSTRAINT node_agent_settings_updated_after_created CHECK (updated_at >= created_at)
);

CREATE TABLE sessions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    csrf_token_hash TEXT NOT NULL,
    source_ip INET,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT sessions_token_hash_not_blank CHECK (btrim(token_hash) <> ''),
    CONSTRAINT sessions_csrf_hash_not_blank CHECK (btrim(csrf_token_hash) <> ''),
    CONSTRAINT sessions_expiry_after_creation CHECK (expires_at > created_at),
    CONSTRAINT sessions_last_seen_after_creation CHECK (last_seen_at >= created_at),
    CONSTRAINT sessions_revoked_after_creation CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE TABLE agent_tokens (
    id UUID PRIMARY KEY,
    node_id UUID NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    label TEXT,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT agent_tokens_hash_not_blank CHECK (btrim(token_hash) <> ''),
    CONSTRAINT agent_tokens_label_not_blank CHECK (label IS NULL OR btrim(label) <> ''),
    CONSTRAINT agent_tokens_expiry_after_creation CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT agent_tokens_revoked_after_creation CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE TABLE enrollment_tokens (
    id UUID PRIMARY KEY,
    node_id UUID NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    used_source_ip INET,
    CONSTRAINT enrollment_tokens_hash_not_blank CHECK (btrim(token_hash) <> ''),
    CONSTRAINT enrollment_tokens_expiry_after_creation CHECK (expires_at > created_at),
    CONSTRAINT enrollment_tokens_used_after_creation CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE TABLE node_metric_current (
    node_id UUID PRIMARY KEY REFERENCES nodes(id) ON DELETE CASCADE,
    sampled_at TIMESTAMPTZ NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    cpu_percent NUMERIC(5,2) NOT NULL,
    load_1 NUMERIC NOT NULL,
    load_5 NUMERIC NOT NULL,
    load_15 NUMERIC NOT NULL,
    uptime_seconds NUMERIC NOT NULL,
    memory_total_bytes BIGINT NOT NULL,
    memory_used_bytes BIGINT NOT NULL,
    memory_available_bytes BIGINT NOT NULL,
    swap_total_bytes BIGINT NOT NULL,
    swap_used_bytes BIGINT NOT NULL,
    network_rx_bps NUMERIC NOT NULL,
    network_tx_bps NUMERIC NOT NULL,
    network_rx_bytes BIGINT NOT NULL,
    network_tx_bytes BIGINT NOT NULL,
    CONSTRAINT node_metric_current_cpu_range CHECK (cpu_percent >= 0 AND cpu_percent <= 100),
    CONSTRAINT node_metric_current_load_nonnegative CHECK (load_1 >= 0 AND load_5 >= 0 AND load_15 >= 0),
    CONSTRAINT node_metric_current_uptime_nonnegative CHECK (uptime_seconds >= 0),
    CONSTRAINT node_metric_current_memory_valid CHECK (
        memory_total_bytes >= 0
        AND memory_used_bytes >= 0
        AND memory_used_bytes <= memory_total_bytes
        AND memory_available_bytes >= 0
        AND memory_available_bytes <= memory_total_bytes
    ),
    CONSTRAINT node_metric_current_swap_valid CHECK (
        swap_total_bytes >= 0
        AND swap_used_bytes >= 0
        AND swap_used_bytes <= swap_total_bytes
    ),
    CONSTRAINT node_metric_current_network_nonnegative CHECK (
        network_rx_bps >= 0
        AND network_tx_bps >= 0
        AND network_rx_bytes >= 0
        AND network_tx_bytes >= 0
    )
);

CREATE TABLE node_metric_ring (
    node_id UUID NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    slot SMALLINT NOT NULL,
    sampled_at TIMESTAMPTZ NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    cpu_percent NUMERIC(5,2) NOT NULL,
    load_1 NUMERIC NOT NULL,
    load_5 NUMERIC NOT NULL,
    load_15 NUMERIC NOT NULL,
    uptime_seconds NUMERIC NOT NULL,
    memory_total_bytes BIGINT NOT NULL,
    memory_used_bytes BIGINT NOT NULL,
    memory_available_bytes BIGINT NOT NULL,
    swap_total_bytes BIGINT NOT NULL,
    swap_used_bytes BIGINT NOT NULL,
    network_rx_bps NUMERIC NOT NULL,
    network_tx_bps NUMERIC NOT NULL,
    network_rx_bytes BIGINT NOT NULL,
    network_tx_bytes BIGINT NOT NULL,
    PRIMARY KEY (node_id, slot),
    CONSTRAINT node_metric_ring_slot_range CHECK (slot >= 0 AND slot <= 59),
    CONSTRAINT node_metric_ring_cpu_range CHECK (cpu_percent >= 0 AND cpu_percent <= 100),
    CONSTRAINT node_metric_ring_load_nonnegative CHECK (load_1 >= 0 AND load_5 >= 0 AND load_15 >= 0),
    CONSTRAINT node_metric_ring_uptime_nonnegative CHECK (uptime_seconds >= 0),
    CONSTRAINT node_metric_ring_memory_valid CHECK (
        memory_total_bytes >= 0
        AND memory_used_bytes >= 0
        AND memory_used_bytes <= memory_total_bytes
        AND memory_available_bytes >= 0
        AND memory_available_bytes <= memory_total_bytes
    ),
    CONSTRAINT node_metric_ring_swap_valid CHECK (
        swap_total_bytes >= 0
        AND swap_used_bytes >= 0
        AND swap_used_bytes <= swap_total_bytes
    ),
    CONSTRAINT node_metric_ring_network_nonnegative CHECK (
        network_rx_bps >= 0
        AND network_tx_bps >= 0
        AND network_rx_bytes >= 0
        AND network_tx_bytes >= 0
    )
);

CREATE TABLE node_disk_current (
    node_id UUID NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    mountpoint TEXT NOT NULL,
    sampled_at TIMESTAMPTZ NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    total_bytes BIGINT NOT NULL,
    used_bytes BIGINT NOT NULL,
    available_bytes BIGINT NOT NULL,
    PRIMARY KEY (node_id, mountpoint),
    CONSTRAINT node_disk_current_mountpoint_not_blank CHECK (btrim(mountpoint) <> ''),
    CONSTRAINT node_disk_current_values_valid CHECK (
        total_bytes >= 0
        AND used_bytes >= 0
        AND used_bytes <= total_bytes
        AND available_bytes >= 0
        AND available_bytes <= total_bytes
    )
);

CREATE TABLE node_disk_ring (
    node_id UUID NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    mountpoint TEXT NOT NULL,
    slot SMALLINT NOT NULL,
    sampled_at TIMESTAMPTZ NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    total_bytes BIGINT NOT NULL,
    used_bytes BIGINT NOT NULL,
    available_bytes BIGINT NOT NULL,
    PRIMARY KEY (node_id, mountpoint, slot),
    CONSTRAINT node_disk_ring_mountpoint_not_blank CHECK (btrim(mountpoint) <> ''),
    CONSTRAINT node_disk_ring_slot_range CHECK (slot >= 0 AND slot <= 59),
    CONSTRAINT node_disk_ring_values_valid CHECK (
        total_bytes >= 0
        AND used_bytes >= 0
        AND used_bytes <= total_bytes
        AND available_bytes >= 0
        AND available_bytes <= total_bytes
    )
);

CREATE TABLE probe_targets (
    id UUID PRIMARY KEY,
    node_id UUID NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    probe_type TEXT NOT NULL,
    host TEXT NOT NULL,
    port INTEGER,
    path TEXT,
    interval_seconds INTEGER NOT NULL DEFAULT 30,
    timeout_seconds INTEGER NOT NULL DEFAULT 3,
    retention_seconds INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    config_version BIGINT NOT NULL DEFAULT 1,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (node_id, name),
    UNIQUE (node_id, id),
    CONSTRAINT probe_targets_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT probe_targets_type_valid CHECK (probe_type IN ('icmp', 'tcp', 'http', 'https')),
    CONSTRAINT probe_targets_host_not_blank CHECK (btrim(host) <> ''),
    CONSTRAINT probe_targets_port_valid CHECK (port IS NULL OR (port >= 1 AND port <= 65535)),
    CONSTRAINT probe_targets_tcp_requires_port CHECK (probe_type <> 'tcp' OR port IS NOT NULL),
    CONSTRAINT probe_targets_icmp_has_no_port CHECK (probe_type <> 'icmp' OR port IS NULL),
    CONSTRAINT probe_targets_path_valid CHECK (
        path IS NULL
        OR (probe_type IN ('http', 'https') AND left(path, 1) = '/')
    ),
    CONSTRAINT probe_targets_interval_range CHECK (interval_seconds >= 10 AND interval_seconds <= 86400),
    CONSTRAINT probe_targets_timeout_range CHECK (
        timeout_seconds >= 1
        AND timeout_seconds <= 60
        AND timeout_seconds <= interval_seconds
    ),
    CONSTRAINT probe_targets_retention_range CHECK (
        retention_seconds > 0
        AND retention_seconds <= 7776000
    ),
    CONSTRAINT probe_targets_config_version_positive CHECK (config_version > 0),
    CONSTRAINT probe_targets_updated_after_created CHECK (updated_at >= created_at)
);

CREATE TABLE processed_batches (
    node_id UUID NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    batch_id UUID NOT NULL,
    sequence BIGINT NOT NULL,
    agent_time TIMESTAMPTZ NOT NULL,
    agent_version TEXT NOT NULL,
    config_version BIGINT NOT NULL,
    payload_checksum TEXT NOT NULL,
    clock_status TEXT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (node_id, batch_id),
    CONSTRAINT processed_batches_sequence_positive CHECK (sequence > 0),
    CONSTRAINT processed_batches_agent_version_not_blank CHECK (btrim(agent_version) <> ''),
    CONSTRAINT processed_batches_config_version_positive CHECK (config_version > 0),
    CONSTRAINT processed_batches_checksum_not_blank CHECK (btrim(payload_checksum) <> ''),
    CONSTRAINT processed_batches_clock_status_valid CHECK (clock_status IN ('ok', 'skewed'))
);

CREATE TABLE probe_result_raw (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    node_id UUID NOT NULL,
    target_id UUID NOT NULL,
    batch_id UUID NOT NULL,
    sample_index INTEGER NOT NULL,
    sampled_at TIMESTAMPTZ NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    sent_count BIGINT NOT NULL,
    received_count BIGINT NOT NULL,
    latency_sum_us BIGINT NOT NULL,
    latency_min_us BIGINT,
    latency_max_us BIGINT,
    http_status_code INTEGER,
    error_code TEXT,
    UNIQUE (node_id, batch_id, sample_index),
    FOREIGN KEY (node_id, target_id) REFERENCES probe_targets(node_id, id) ON DELETE CASCADE,
    FOREIGN KEY (node_id, batch_id) REFERENCES processed_batches(node_id, batch_id),
    CONSTRAINT probe_result_raw_sample_index_nonnegative CHECK (sample_index >= 0),
    CONSTRAINT probe_result_raw_counts_valid CHECK (
        sent_count > 0
        AND received_count >= 0
        AND received_count <= sent_count
    ),
    CONSTRAINT probe_result_raw_latency_valid CHECK (
        latency_sum_us >= 0
        AND (
            (received_count = 0 AND latency_sum_us = 0 AND latency_min_us IS NULL AND latency_max_us IS NULL)
            OR
            (received_count > 0 AND latency_min_us IS NOT NULL AND latency_max_us IS NOT NULL
                AND latency_min_us >= 0 AND latency_max_us >= latency_min_us
                AND latency_sum_us::NUMERIC >= latency_min_us::NUMERIC * received_count
                AND latency_sum_us::NUMERIC <= latency_max_us::NUMERIC * received_count)
        )
    ),
    CONSTRAINT probe_result_raw_http_status_valid CHECK (
        http_status_code IS NULL OR (http_status_code >= 100 AND http_status_code <= 599)
    ),
    CONSTRAINT probe_result_raw_error_code_valid CHECK (
        error_code IS NULL
        OR (
            btrim(error_code) <> ''
            AND char_length(error_code) <= 128
            AND error_code !~ '[\r\n]'
            AND error_code !~ '^[[:space:]]|[[:space:]]$'
        )
    )
);

CREATE TABLE probe_result_5m (
    target_id UUID NOT NULL REFERENCES probe_targets(id) ON DELETE CASCADE,
    bucket_start TIMESTAMPTZ NOT NULL,
    result_count INTEGER NOT NULL,
    sent_count BIGINT NOT NULL,
    received_count BIGINT NOT NULL,
    latency_sum_us NUMERIC NOT NULL,
    latency_min_us BIGINT,
    latency_max_us BIGINT,
    PRIMARY KEY (target_id, bucket_start),
    CONSTRAINT probe_result_5m_results_positive CHECK (result_count > 0),
    CONSTRAINT probe_result_5m_counts_valid CHECK (
        sent_count > 0
        AND received_count >= 0
        AND received_count <= sent_count
    ),
    CONSTRAINT probe_result_5m_latency_valid CHECK (
        latency_sum_us >= 0
        AND (
            (received_count = 0 AND latency_sum_us = 0 AND latency_min_us IS NULL AND latency_max_us IS NULL)
            OR
            (received_count > 0 AND latency_min_us IS NOT NULL AND latency_max_us IS NOT NULL
                AND latency_min_us >= 0 AND latency_max_us >= latency_min_us
                AND latency_sum_us::NUMERIC >= latency_min_us::NUMERIC * received_count
                AND latency_sum_us::NUMERIC <= latency_max_us::NUMERIC * received_count)
        )
    )
);

CREATE TABLE probe_result_1h (
    target_id UUID NOT NULL REFERENCES probe_targets(id) ON DELETE CASCADE,
    bucket_start TIMESTAMPTZ NOT NULL,
    result_count INTEGER NOT NULL,
    sent_count BIGINT NOT NULL,
    received_count BIGINT NOT NULL,
    latency_sum_us NUMERIC NOT NULL,
    latency_min_us BIGINT,
    latency_max_us BIGINT,
    PRIMARY KEY (target_id, bucket_start),
    CONSTRAINT probe_result_1h_results_positive CHECK (result_count > 0),
    CONSTRAINT probe_result_1h_counts_valid CHECK (
        sent_count > 0
        AND received_count >= 0
        AND received_count <= sent_count
    ),
    CONSTRAINT probe_result_1h_latency_valid CHECK (
        latency_sum_us >= 0
        AND (
            (received_count = 0 AND latency_sum_us = 0 AND latency_min_us IS NULL AND latency_max_us IS NULL)
            OR
            (received_count > 0 AND latency_min_us IS NOT NULL AND latency_max_us IS NOT NULL
                AND latency_min_us >= 0 AND latency_max_us >= latency_min_us
                AND latency_sum_us::NUMERIC >= latency_min_us::NUMERIC * received_count
                AND latency_sum_us::NUMERIC <= latency_max_us::NUMERIC * received_count)
        )
    )
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actor_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    actor_username TEXT,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    source_ip INET,
    request_id TEXT NOT NULL,
    before_summary JSONB,
    after_summary JSONB,
    result TEXT NOT NULL,
    error_code TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_action_not_blank CHECK (btrim(action) <> ''),
    CONSTRAINT audit_logs_target_type_not_blank CHECK (target_type IS NULL OR btrim(target_type) <> ''),
    CONSTRAINT audit_logs_target_id_not_blank CHECK (target_id IS NULL OR btrim(target_id) <> ''),
    CONSTRAINT audit_logs_request_id_not_blank CHECK (btrim(request_id) <> ''),
    CONSTRAINT audit_logs_result_valid CHECK (result IN ('success', 'failure')),
    CONSTRAINT audit_logs_error_code_not_blank CHECK (error_code IS NULL OR btrim(error_code) <> '')
);

CREATE TABLE job_watermarks (
    job_name TEXT PRIMARY KEY,
    watermark_at TIMESTAMPTZ,
    details JSONB NOT NULL DEFAULT '{}'::JSONB,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT job_watermarks_name_not_blank CHECK (btrim(job_name) <> '')
);

CREATE INDEX users_role_enabled_idx
    ON users (role, enabled);

CREATE INDEX nodes_last_received_idx
    ON nodes (last_received_at DESC NULLS LAST);

CREATE INDEX nodes_enabled_idx
    ON nodes (enabled);

CREATE INDEX sessions_user_active_idx
    ON sessions (user_id, expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX sessions_expiry_idx
    ON sessions (expires_at);

CREATE INDEX agent_tokens_node_active_idx
    ON agent_tokens (node_id, created_at DESC)
    WHERE revoked_at IS NULL;

CREATE INDEX agent_tokens_expiry_idx
    ON agent_tokens (expires_at)
    WHERE expires_at IS NOT NULL AND revoked_at IS NULL;

CREATE INDEX enrollment_tokens_node_active_idx
    ON enrollment_tokens (node_id, expires_at)
    WHERE used_at IS NULL;

CREATE INDEX enrollment_tokens_expiry_idx
    ON enrollment_tokens (expires_at)
    WHERE used_at IS NULL;

CREATE INDEX node_metric_ring_sampled_idx
    ON node_metric_ring (effective_at);

CREATE INDEX node_disk_ring_sampled_idx
    ON node_disk_ring (effective_at);

CREATE INDEX probe_targets_node_enabled_idx
    ON probe_targets (node_id, enabled, config_version);

CREATE INDEX processed_batches_received_idx
    ON processed_batches (received_at);

CREATE INDEX processed_batches_node_sequence_idx
    ON processed_batches (node_id, sequence DESC);

CREATE INDEX probe_result_raw_target_sampled_idx
    ON probe_result_raw (target_id, effective_at DESC);

CREATE INDEX probe_result_raw_node_sampled_idx
    ON probe_result_raw (node_id, effective_at DESC);

CREATE INDEX probe_result_raw_received_idx
    ON probe_result_raw (received_at);

CREATE INDEX probe_result_5m_bucket_idx
    ON probe_result_5m (bucket_start);

CREATE INDEX probe_result_1h_bucket_idx
    ON probe_result_1h (bucket_start);

CREATE INDEX audit_logs_occurred_idx
    ON audit_logs (occurred_at DESC);

CREATE INDEX audit_logs_actor_occurred_idx
    ON audit_logs (actor_user_id, occurred_at DESC);

COMMENT ON TABLE node_metric_ring IS
    'Fixed 60-slot ring. Queries must also require effective_at > CURRENT_TIMESTAMP - INTERVAL ''5 minutes''.';

COMMENT ON TABLE node_disk_ring IS
    'Fixed 60-slot-per-mountpoint ring. Queries must also require effective_at > CURRENT_TIMESTAMP - INTERVAL ''5 minutes''.';

COMMENT ON COLUMN probe_result_raw.effective_at IS
    'Server-normalized timestamp used for retention and aggregation; sampled_at preserves the original Agent clock value.';

COMMENT ON COLUMN probe_targets.retention_seconds IS
    'Per-target trend retention. Database-enforced maximum is 7776000 seconds (90 days).';

COMMENT ON TABLE processed_batches IS
    'Short-lived exact-idempotency ledger. The node row sequence high-water mark permanently rejects old replays after ledger cleanup.';

COMMENT ON COLUMN nodes.last_accepted_sequence IS
    'Persistent Agent report sequence high-water mark. Lock and advance it atomically with every newly accepted batch.';
